Vagrant.configure("2") do |config|

    config.vm.box = "cheretbe/routeros"
    config.vm.provision "routeros_file", name: "Upload test", source: "script.rsc", destination: "script.rsc"
    config.vm.provision "routeros_command", name: "Exec custom script", command: "/import script.rsc", check_script_error: true
    config.vm.network "private_network", ip: "192.168.33.100"
    config.vm.network "private_network", virtualbox__intnet: "vagrant-intnet-2", auto_config: false
    config.vm.network "private_network", virtualbox__intnet: "vagrant-intnet-3", auto_config: false
    config.vm.network "private_network", virtualbox__intnet: "vagrant-intnet-4", auto_config: false
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
  